# Generated by Django 2.2.4 on 2019-08-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
